POST http://localhost:8080/user
Content-Type: application/json

{
  "userName": "Admin",
  "firstName": "First",
  "lastName": "Fwast",
  "email": "fwqfllq@mail.ru",
  "password": "passwod",
  "phone": [
    "80440009998",
    "+375291259489"
  ],
  "userStatus": "2",
  "address":
  {
    "street": "street",
    "houseNumber":"23a",
    "city": "city"
  }
}


###
POST http://localhost:8080/user/auth
Content-Type: application/json

{
  "userName": "Userame5",
  "password": "passwod"
}


###

GET http://localhost:8080/user/Userame5


###

DELETE http://localhost:8080/user/Userame5


###

POST http://localhost:8080/tag
Content-Type: application/json
X-Token: 46c2ee91-02da-4936-87e9-7b6c35d7f1f0

{
"name": "Tjoiiu"
}

###


PUT http://localhost:8080/user/Userame5
Content-Type: application/json

{
  "userName": "Userame5",
  "firstName": "Test",
  "lastName": "Fwaste",
  "email": "fwqfllq@mail.ru",
  "password": "passwod",
  "phone": "80445729199",
  "userStatus": "33"
}

###
POST http://localhost:8080/pet
Content-Type: application/json
X-Token: dc944bef-c6fc-4748-8bbc-9e62a8d8aca3

{
  "name": "Ptyuw",
  "status": "PENDING",
  "tags": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ],
  "category":
  {
    "name": "Eeef"
  }
}

###

PUT http://localhost:8080/pet
Content-Type: application/json

{
  "id": 1,
  "name": "Name",
  "status": "PENDING",
  "tags": [
    {
      "id": 3
    },
    {
      "id": 4
    }
  ],
  "category":
  {
    "name": "Eeef"
  }
}


###

GET http://localhost:8080/pet/findAllByStatus?status=PENDING
X-Token: dc944bef-c6fc-4748-8bbc-9e62a8d8aca3


###

DELETE http://localhost:8080/pet/1
X-Token: 34b98525-a5f2-49a7-b01c-144f4c632c27
###

POST http://localhost:8080/store/order
Content-Type: application/json

{
  "petId": 1,
  "quantity": 1,
  "shipDate": "2020-11-12",
  "status": "DELIVERED",
  "complete": true
}

###

GET http://localhost:8080/store/order/1

###

DELETE http://localhost:8080/store/order/1

###

GET http://localhost:8080/store/order/inventory

